### ISSUE TITLE
Add support for webpack-dashboard

### ISSUE THREAD

**Issue by lakhman** [mariusbalcytis/webpack-bundle#21]
Awesome new library here: https://github.com/FormidableLabs/webpack-dashboard

Running the line generated by process via the command line works, but doing it via symfony console command doesn't. It seems to infinitely remain within the while loop waiting for the configuration to dump.

https://github.com/mariusbalcytis/webpack-bundle/blob/master/src/Compiler/WebpackCompiler.php#L106

```bash
'node_modules/.bin/webpack-dashboard' '--' 'node_modules/.bin/webpack-dev-server' '--config' '/path/to/app/var/cache/dev/webpack.config.js' '--hot' '--silent' '--no-info' 
```

This would be awesome to get working, checkout the screenshot on the project page. I want to work for nasa, this is good practice in using their systems.. haha!

Any ideas why the config file is not dumping?

**Comment by mariusbalcytis** [comment]
Thanks for the link and the idea! Work for NASA? Who doesn't want that! ;)

- TTY support was missing, added using hint in #20
- prefix configuration options were added for TTY mode - it's not enabled in all distributions. `webpack-dashboard` without TTY does not look anywhere near NASA
- library was added by default (in `package.json`), TTY command prefix for `dev-server` was also added to use dashboard by default
- `webpack:compile` does not work well with dashboard. It can work, but it hangs after job is done and there currently is no way to change that. See [this issue](https://github.com/FormidableLabs/webpack-dashboard/issues/96) for details. I've left out the dashboard there so that compiling assets would be hassle-free in CI and testing environments

Currently only in master, I'll tag a release after a day or few with extra features.

**Comment by lakhman** [comment]
This is awesome! thank you!

When I exit webpack-dashboard (using CTRL+C), sometimes the process is not killed. If you exit the dashboard, then try start it again, you get error message "ADDR IN USE" - it was not killed and is still running in the background (this doesn't happen always).

I use the following to view the process list and kill it manually.

``` bash
ps aux | grep webpack
# user     10737   0.0  2.1  3435412 354464   ??  Ss    4:28PM   0:24.61 node node_modules/webpack-dev-server/bin/webpack-dev-server.js --config /Sites/app/var/cache/dev/webpack.config.js --hot --silent --no-info --history-api-fallback --inline --display-reasons --progress --colors

# Kill it
kill -9 10737

# Restart (Assuming bin is on your path - PATH="./bin:$PATH")
console m:w:d
```

I think this is an issue with webpack-dashboard, not this plugin, but if we know the process ID when the user terminates it, can we check and kill it manually?

Other then that, this works great! when compiling it boots the dashboard, then you have to exit it for the compile to complete (else you still get the "manifest file not found error". Not sure how this would work in a CI environment, maybe i'm using an incorrect configuration?

--------------

Can you recommend the configuration to use in the yaml file?

        # This works, but is it ideal? - I see a working dashboard "compiling" but requires user input to complete
       # I suspect this config may be causing this issue?
        dev_server:
            arguments:  # What should be recommended for webpack-dashboard?
                - --hot
                - --silent
                - --no-info
                - --history-api-fallback
                - --inline
                - --display-reasons
                - --progress
                - --colors

--------------

Awesome stuff! thanks so much! - webpack-dashboard is awesome!! 👍

**Comment by lakhman** [comment]
Sorry, compiling works, I didn't update this line in my webpack config:

```js
    if (process.env.WEBPACK_MODE === 'watch' && process.env.TTY_MODE === 'on') {
        config.plugins.push(new DashboardPlugin());
    }
```

This fixed the issue with having to manually exit from dashboard.

**Comment by lakhman** [comment]
If you're interested, webpack-dashboard uses https://github.com/chjj/blessed to output such nice terminal output.

**Comment by mariusbalcytis** [comment]
About `dev_server` arguments:
- don't know what `silent` or `display-reasons` does, I don't see any difference and I don't see any documentation about them
- `colors` is not needed - it displays correctly when in TTY mode (otherwise dashboard would not work)
- `progress` - I don't see the point as dashboard shows the progress
- all other except `no-info` - default ones

So, additional option to default ones is `no-info`. I'd use it with dashboard, as all assets are visible in other panes.

Unfortunately, I cannot reproduce the zombie process case - I've tried several times with different configurations with no success (or, ehm, failure). Seems that dashboard kills the process correctly, at least in my environment.
